version: '3'

vars:
  REGISTRY: 'ttl.sh/protect'

tasks:
  build-image:
    vars:
      IMAGE: 'protect-webhook'
    cmds: 
      - docker buildx build --platform linux/amd64 -t {{ .REGISTRY }}/{{ .IMAGE }}:latest .
      - echo "Built {{ .REGISTRY }}/{{ .IMAGE }}:latest"
      - docker push {{ .REGISTRY }}/{{ .IMAGE }}:latest

  install-cert-manager:
    cmds:
      - helm repo add jetstack https://charts.jetstack.io
      - helm repo update
      - |
        helm install cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --set installCRDs=true

  install-self-signed-certs:
    preconditions:
      - test -f ./examples/self-signed-certs/self-signed-certs.yaml
    cmds:
      - kubectl create namespace edera-system
      - kubectl apply -f ./examples/self-signed-certs/self-signed-certs.yaml -n edera-system

  chart-test:
    cmds:
      - ct install --target-branch main --namespace edera-system
