apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "protect-webhook.fullname" . }}
  labels:
    {{- include "protect-webhook.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: {{ include "protect-webhook.fullname" . }}.edera.dev
    clientConfig:
      service:
        name: {{ include "protect-webhook.fullname" . }}
        namespace: {{ .Values.webhook.serviceNamespace | default .Release.Namespace }}
        path: /mutate
    # Automatically exclude Edera resources
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values: [{{ .Release.Namespace }}]
    {{- if .Values.webhook }}
    {{- if .Values.webhook.objectSelector }}
    objectSelector:
      {{- with .Values.webhook.objectSelector.matchLabels }}
      matchLabels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Ignore" }}
    {{- end }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
